-- ============================================================================
-- 001 — Esquema inicial
-- Fecha: 2026-08-22
--
-- Reconstruye el estado del esquema tal como existe en producción al momento
-- de empezar a versionar la base. Los cambios anteriores a esta fecha se
-- aplicaron directamente sobre Supabase sin registro: esta migración cierra
-- ese hueco y establece el punto de partida.
--
-- ORDEN: las tablas se crean respetando sus dependencias. Una tabla con clave
-- foránea no puede crearse antes que la tabla a la que apunta.
--
--   Nivel 1  sedes · contactos · politicas_privacidad
--   Nivel 2  usuarios · motos
--   Nivel 3  fotos_motos · intenciones · ventas · compras · permutas · leads_chat
--   Nivel 4  conversaciones · mensajes
--   Vistas   reportes (dependen de las tablas)
--
-- IDEMPOTENCIA: todo usa "if not exists" para que ejecutar este archivo dos
-- veces no falle. Aplicar una migración debe ser seguro de repetir.
-- ============================================================================


-- ============================================================================
-- NIVEL 1 — Tablas sin dependencias
-- ============================================================================

-- Sedes físicas del negocio.
create table if not exists sedes (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz default now(),
    nombre      text not null,
    direccion   text not null,
    telefono    text,
    horario     text,
    activa      boolean default true
);

-- Contactos que escriben por canales de mensajería.
create table if not exists contactos (
    id               bigint generated by default as identity primary key,
    telefono         text not null unique,
    canal            text not null default 'whatsapp',
    primer_contacto  timestamptz not null default now()
);

-- Versiones históricas de la política de tratamiento de datos.
--
-- No basta con registrar QUE alguien consintió: hay que poder demostrar A QUÉ
-- consintió. Cada versión se archiva con su texto completo y un hash SHA-256
-- que permite probar que no fue alterada después.
--
-- vigente_hasta en null identifica a la versión actual.
create table if not exists politicas_privacidad (
    id             bigint generated by default as identity primary key,
    version        text not null unique,
    texto          text not null,
    hash_texto     text,
    vigente_desde  timestamptz not null,
    vigente_hasta  timestamptz,
    created_at     timestamptz not null default now()
);


-- ============================================================================
-- NIVEL 2 — Dependen del nivel 1
-- ============================================================================

-- Usuarios del panel: admin, asesor y gerencia.
--
-- La contraseña se guarda hasheada (scrypt vía Werkzeug), nunca en texto plano.
-- 'activo' permite desactivar el acceso sin borrar el registro histórico.
-- 'whatsapp' es la línea propia de cada asesor, usada en la atribución.
--
-- PENDIENTE: 'rol' es texto libre. Debería restringirse con un check a los
-- tres valores válidos (ver migración futura).
create table if not exists usuarios (
    id               bigint generated by default as identity primary key,
    created_at       timestamptz default now(),
    usuario          text not null unique,
    password_hash    text not null,
    nombre_completo  text not null,
    rol              text not null default 'asesor',
    sede_id          bigint references sedes(id) on delete restrict,
    activo           boolean default true,
    whatsapp         text
);

-- Inventario de motocicletas.
--
-- 'estado' controla la visibilidad pública: solo las 'disponible' aparecen en
-- el catálogo, el sitemap y el contexto del asistente.
create table if not exists motos (
    id           bigint generated by default as identity primary key,
    created_at   timestamptz default now(),
    marca        text not null,
    modelo       text not null,
    anio         integer,
    color        text,
    precio       bigint,
    kilometraje  integer,
    foto_url     text,
    foto_path    text,
    video_path   text,
    estado       text default 'disponible',
    descripcion  text,
    soat         text,
    tecno        text,
    placa        text,
    cilindraje   integer,
    sede_id      bigint default 1 references sedes(id) on delete restrict
);


-- ============================================================================
-- NIVEL 3 — Dependen de motos y usuarios
-- ============================================================================

-- Galería de fotos. CASCADE: las fotos de una moto borrada no sirven a nadie.
create table if not exists fotos_motos (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz default now(),
    moto_id     bigint references motos(id) on delete cascade,
    foto_url    text,
    foto_path   text,
    orden       integer default 0
);

-- Registro de clics en "preguntar por esta moto". Alimenta los reportes de
-- interés por moto y por marca.
create table if not exists intenciones (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz default now(),
    moto_id     bigint references motos(id) on delete cascade,
    sede_id     bigint references sedes(id) on delete set null
);

-- Registro histórico de ventas.
--
-- descripcion, usuario_nombre y placa se CONGELAN como texto además de las
-- referencias: si la moto se borra o el usuario cambia de nombre, el reporte
-- sigue siendo legible. Desnormalización intencional.
--
-- SET NULL en las foráneas por la misma razón: el registro de una venta no
-- debe desaparecer porque se borre la moto.
--
-- 'verificada' permite que gerencia valide contra la contabilidad. Quien
-- verifica se toma de la sesión, nunca del formulario.
create table if not exists ventas (
    id              bigint generated by default as identity primary key,
    created_at      timestamptz default now(),
    moto_id         bigint references motos(id) on delete set null,
    descripcion     text not null,
    usuario_id      bigint references usuarios(id) on delete set null,
    usuario_nombre  text not null,
    sede_id         bigint references sedes(id) on delete set null,
    placa           text,
    verificada      boolean not null default false,
    verificada_por  text,
    verificada_en   timestamptz
);

-- Registro histórico de compras. Mismo patrón que ventas.
create table if not exists compras (
    id              bigint generated by default as identity primary key,
    moto_id         bigint not null references motos(id),
    usuario_id      bigint not null references usuarios(id),
    usuario_nombre  text not null,
    created_at      timestamptz not null default now(),
    descripcion     text not null default '',
    placa           text,
    verificada      boolean not null default false,
    verificada_por  text,
    verificada_en   timestamptz
);

-- Permutas: entra una moto, sale otra. Enlaza ambas y al asesor.
create table if not exists permutas (
    id                    bigint generated by default as identity primary key,
    moto_entrante_id      bigint not null references motos(id),
    moto_saliente_id      bigint not null references motos(id),
    descripcion_entrante  text not null,
    descripcion_saliente  text not null,
    usuario_id            bigint not null references usuarios(id),
    usuario_nombre        text not null,
    created_at            timestamptz not null default now()
);

-- Leads de financiación captados por el asistente de IA.
--
-- Tres grupos de columnas:
--
--   1. Contacto y simulación (texto plano): nombre, teléfono, correo, montos.
--
--   2. Datos financieros CIFRADOS: ingresos, reporte en centrales e historial
--      crediticio. Se guardan con Fernet; la clave vive en variables de
--      entorno, nunca en la base. Están PREPARADOS pero DESACTIVADOS: son
--      datos regulados por la Ley 1266 y se activarán solo con asesoría legal.
--
--   3. Consentimiento (Ley 1581): dos niveles de autorización, fecha, y la
--      versión exacta de la política que el cliente aceptó.
--
-- version_politica duplica el dato de politica_id a propósito: si la tabla de
-- políticas se migrara o perdiera, el lead conserva a qué versión consintió.
create table if not exists leads_chat (
    id                          bigint generated by default as identity primary key,
    created_at                  timestamptz not null default now(),
    origen                      text not null default 'chat',

    nombre                      text not null,
    telefono                    text not null,
    correo                      text,
    moto_id                     bigint references motos(id),
    valor_financiar             bigint,
    cuota_inicial               bigint default 0,
    plazo_meses                 integer,
    cuota_calculada             bigint,

    ingresos_cifrado            text,
    reportado_cifrado           text,
    vida_crediticia_cifrado     text,
    tipo_entidad_sugerida       text,

    autorizo_datos_basicos      boolean not null default false,
    autorizo_datos_financieros  boolean not null default false,
    fecha_consentimiento        timestamptz,
    politica_id                 bigint references politicas_privacidad(id),
    version_politica            text
);


-- ============================================================================
-- NIVEL 4 — Mensajería
-- ============================================================================

create table if not exists conversaciones (
    id               bigint generated by default as identity primary key,
    contacto_id      bigint not null references contactos(id),
    canal            text not null default 'whatsapp',
    moto_id          bigint references motos(id),
    venta_id         bigint references ventas(id),
    iniciada         timestamptz not null default now(),
    ultimo_mensaje   timestamptz not null default now()
);

-- Registro de consumo por mensaje, para controlar el gasto de tokens.
create table if not exists mensajes (
    id               bigint generated by default as identity primary key,
    conversacion_id  bigint not null references conversaciones(id),
    nivel            integer not null,
    tokens_entrada   integer not null default 0,
    tokens_salida    integer not null default 0,
    modelo           text,
    created_at       timestamptz not null default now()
);


-- ============================================================================
-- ÍNDICES
--
-- Los de clave primaria y unique los crea Postgres solo. Estos son los
-- creados a propósito para acelerar consultas concretas.
-- ============================================================================

-- Índice único PARCIAL: impide dos motos DISPONIBLES con la misma placa, pero
-- permite que una placa se repita entre motos ya vendidas. Una misma moto
-- puede entrar, venderse, y volver a entrar años después.
create unique index if not exists idx_placa_unica_disponible
    on motos (placa)
    where estado = 'disponible' and placa is not null;

-- Aceleran los reportes de gerencia.
create index if not exists idx_intenciones_moto on intenciones (moto_id);
create index if not exists idx_ventas_fecha     on ventas (created_at);
create index if not exists idx_ventas_usuario   on ventas (usuario_id);


-- ============================================================================
-- SEGURIDAD — RLS
--
-- RLS funciona como lista blanca: con RLS activo y sin políticas, NADIE pasa.
-- Es el comportamiento por defecto más seguro.
--
-- Solo tres tablas necesitan lectura pública (las que alimentan el catálogo).
-- Las demás quedan sin políticas: inaccesibles salvo para service_role, que
-- bypassa RLS por diseño.
-- ============================================================================

alter table sedes                enable row level security;
alter table contactos            enable row level security;
alter table politicas_privacidad enable row level security;
alter table usuarios             enable row level security;
alter table motos                enable row level security;
alter table fotos_motos          enable row level security;
alter table intenciones          enable row level security;
alter table ventas               enable row level security;
alter table compras              enable row level security;
alter table permutas             enable row level security;
alter table leads_chat           enable row level security;
alter table conversaciones       enable row level security;
alter table mensajes             enable row level security;

-- Lectura pública SOLO de lo que el catálogo necesita mostrar.
-- Nótese: SELECT únicamente, nunca ALL. El público lee, no escribe.
drop policy if exists "lectura publica de motos" on motos;
create policy "lectura publica de motos"
    on motos for select to anon using (true);

drop policy if exists "lectura publica de sedes" on sedes;
create policy "lectura publica de sedes"
    on sedes for select to anon using (true);

drop policy if exists "lectura publica de fotos" on fotos_motos;
create policy "lectura publica de fotos"
    on fotos_motos for select to anon using (true);


-- ============================================================================
-- PERMISOS
--
-- RLS controla QUÉ FILAS ve un rol; los GRANT controlan si el rol tiene
-- permiso sobre la tabla en absoluto. Son mecanismos independientes: un rol
-- necesita AMBOS. Olvidar el grant a service_role produce un error 42501
-- ("permission denied") aunque RLS esté bien configurado.
-- ============================================================================

grant select, insert, update, delete on all tables in schema public to service_role;

-- El público solo lee las tres tablas del catálogo.
grant select on motos, sedes, fotos_motos to anon;


-- ============================================================================
-- VISTAS DE REPORTE
--
-- Van al final porque dependen de las tablas. Encapsulan las agregaciones que
-- consume el panel de gerencia.
-- ============================================================================

create or replace view reporte_ventas_por_usuario as
    select usuario_nombre,
           count(*) as total_ventas,
           min(created_at) as primera_venta,
           max(created_at) as ultima_venta
    from ventas
    group by usuario_nombre
    order by count(*) desc;

-- La zona horaria importa: sin el AT TIME ZONE, una venta del domingo por la
-- noche en Bogotá caería en la semana siguiente (UTC).
create or replace view reporte_ventas_por_semana as
    select (date_trunc('week', created_at at time zone 'America/Bogota'))::date as semana,
           count(*) as ventas
    from ventas
    group by 1
    order by 1 desc;

-- LEFT JOIN a propósito: una moto borrada del inventario conserva sus
-- consultas históricas, aunque sus datos aparezcan en null.
create or replace view reporte_motos_consultadas as
    select i.moto_id, m.marca, m.modelo, m.anio, m.estado,
           count(*) as consultas
    from intenciones i
    left join motos m on m.id = i.moto_id
    group by i.moto_id, m.marca, m.modelo, m.anio, m.estado
    order by count(*) desc;

create or replace view reporte_consultas_por_marca as
    select m.marca, count(*) as consultas
    from intenciones i
    join motos m on m.id = i.moto_id
    group by m.marca
    order by count(*) desc;

create or replace view reporte_permutas_por_usuario as
    select usuario_nombre, count(*) as total_permutas
    from permutas
    group by usuario_nombre
    order by count(*) desc;

-- UNION ALL junta entrantes y salientes en una sola columna antes de contar:
-- lo que interesa es qué modelos se mueven, sin importar en qué dirección.
create or replace view reporte_modelos_permutados as
    select descripcion, count(*) as veces
    from (
        select descripcion_entrante as descripcion from permutas
        union all
        select descripcion_saliente as descripcion from permutas
    ) todas_las_motos
    group by descripcion
    order by count(*) desc;

grant select on all tables in schema public to service_role;


-- ============================================================================
-- FIN DE LA MIGRACIÓN 001
-- ============================================================================